CREATE VIEW [ASSET_ACCOUNTING].[LAND_ASSET_TRANSFORM_VW]
(
	"ASSET_ID", "GROUP_ID", "OWNER", "MAIN_CLASS", "TRANS_TYPE","ACQDISTYPE", "ACQDISDATE", "ACQDISCOST",
	"ACQDISPSOURCE",
	"ASSET_TYPE", "PID", "REPL_COST", "HECTARES", "LAND_NAME", "SERV_CAT","HRWC_FLAG", "PARK_ID", "PARK_NAME",
	"ADDDATE","MODDATE"
) AS
SELECT DISTINCT
	SDEADM.LND_HRM_PARCEL.ASSET_ID,
	SDEADM.LND_HRM_PARCEL.GROUP_ID,
	SDEADM.LND_HRM_PARCEL.OWNER,
	SDEADM.LND_HRM_PARCEL.ASSETCODE as MAIN_CLASS,
	SDEADM.LND_ACQUISITION_DISPOSAL.TRANS_TYPE,
	SDEADM.LND_ACQUISITION_DISPOSAL.ACQDISTYPE,
	SDEADM.LND_ACQUISITION_DISPOSAL.ACQDISDATE,
	SDEADM.LND_ACQUISITION_DISPOSAL.ACQDISCOST,
	SDEADM.LND_ACQUISITION_DISPOSAL.SOURCE,  -- NEW
	'LAND'  ASSET_TYPE,
	SDEADM.LND_HRM_PARCEL.PID,
	SDEADM.LND_HRM_PARCEL.REPLCSRA as REPL_COST,
	SDEADM.LND_HRM_PARCEL.HECTARES,
	SDEADM.LND_LAND_GROUP.LAND_NAME,
	SDEADM.LND_LAND_GROUP.SERV_CAT,
	NULL HRWC_FLAG,
	SDEADM.LND_HRM_PARK.PARK_ID,
	SDEADM.LND_HRM_PARK.PARK_NAME,
	CAST(SDEADM.LND_HRM_PARCEL.ADDDATE as [date]) ADDDATE,
	CAST(SDEADM.LND_HRM_PARCEL.MODDATE as [date]) MODDATE
FROM
	SDEADM.LND_HRM_PARCEL_HAS_ACQ_DISP

	RIGHT JOIN SDEADM.LND_HRM_PARCEL
		ON SDEADM.LND_HRM_PARCEL_HAS_ACQ_DISP.ASSET_ID = SDEADM.LND_HRM_PARCEL.ASSET_ID

	LEFT JOIN SDEADM.LND_ACQUISITION_DISPOSAL
		ON SDEADM.LND_HRM_PARCEL_HAS_ACQ_DISP.ACQDISP_ID = SDEADM.LND_ACQUISITION_DISPOSAL.ACQDISP_ID

	LEFT JOIN SDEADM.LND_LAND_GROUP
		ON SDEADM.LND_HRM_PARCEL.GROUP_ID = SDEADM.LND_LAND_GROUP.GROUP_ID

	LEFT JOIN SDEADM.LND_HRM_PARK
		ON SDEADM.LND_HRM_PARCEL.GROUP_ID = SDEADM.LND_HRM_PARK.GROUP_ID

WHERE
	SDEADM.LND_HRM_PARCEL.OWNER ='HRM'
	AND SDEADM.LND_HRM_PARCEL.ASSETCODE != 'BSP'
	AND SDEADM.LND_HRM_PARCEL.ASSETCODE != 'ROW'

UNION

SELECT DISTINCT
	SDEADM.LND_HRM_PARCEL.ASSET_ID,
	SDEADM.LND_HRM_PARCEL.GROUP_ID,
	SDEADM.LND_HRM_PARCEL.OWNER,
	SDEADM.LND_HRM_PARCEL.ASSETCODE as MAIN_CLASS,
	SDEADM.LND_ACQUISITION_DISPOSAL.TRANS_TYPE,
	SDEADM.LND_ACQUISITION_DISPOSAL.ACQDISTYPE,
	SDEADM.LND_ACQUISITION_DISPOSAL.ACQDISDATE,
	SDEADM.LND_ACQUISITION_DISPOSAL.ACQDISCOST,
	SDEADM.LND_ACQUISITION_DISPOSAL.SOURCE,  -- NEW
	'LAND' ASSET_TYPE,
	SDEADM.LND_HRM_PARCEL.PID,
	SDEADM.LND_HRM_PARCEL.REPLCSRA as REPL_COST,
	SDEADM.LND_HRM_PARCEL.HECTARES,
	SDEADM.LND_LAND_GROUP.LAND_NAME,
	SDEADM.LND_LAND_GROUP.SERV_CAT,
	NULL HRWC_FLAG,
	SDEADM.LND_HRM_PARK.PARK_ID,
	SDEADM.LND_HRM_PARK.PARK_NAME,
	CAST(SDEADM.LND_HRM_PARCEL.ADDDATE as [date]) ADDDATE,
	CAST(SDEADM.LND_HRM_PARCEL.MODDATE as [date]) MODDATE

FROM
	SDEADM.LND_HRM_PARCEL_HAS_ACQ_DISP

	RIGHT JOIN SDEADM.LND_HRM_PARCEL
		ON SDEADM.LND_HRM_PARCEL_HAS_ACQ_DISP.ASSET_ID = SDEADM.LND_HRM_PARCEL.ASSET_ID

	LEFT JOIN SDEADM.LND_ACQUISITION_DISPOSAL
		ON SDEADM.LND_HRM_PARCEL_HAS_ACQ_DISP.ACQDISP_ID = SDEADM.LND_ACQUISITION_DISPOSAL.ACQDISP_ID

	LEFT JOIN SDEADM.LND_LAND_GROUP
		ON SDEADM.LND_HRM_PARCEL.GROUP_ID = SDEADM.LND_LAND_GROUP.GROUP_ID

	LEFT JOIN SDEADM.LND_HRM_PARK
		ON SDEADM.LND_HRM_PARCEL.GROUP_ID = SDEADM.LND_HRM_PARK.GROUP_ID

WHERE
(
	SDEADM.LND_ACQUISITION_DISPOSAL.TRANS_TYPE = 2  -- DISPOSAL
	AND
	SDEADM.LND_HRM_PARCEL.ASSETCODE NOT IN ('BSP','ROW')
)
OR
(
	SDEADM.LND_ACQUISITION_DISPOSAL.TRANS_TYPE=1  -- ACQUIISTION
	AND
	SDEADM.LND_HRM_PARCEL.OWNER<>'HRM'
	AND
	SDEADM.LND_HRM_PARCEL.ASSETCODE NOT IN ('BSP', 'ROW')
)
